### ISSUE TITLE
What is "This function is every interesting for ASC (https://asc-community.org)"?

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#17]
https://github.com/asc-community/MathS/blob/f8ca3cc39442fabef18e6a8da0c306729ef01294/AngouriMath/Convenience/MathS.cs#L107-L123

**Comment by WhiteBlackGoose** [comment]
Thank you for your notes. Unfortunately, our site is down right now, but we will surely fix it. This function is being investigated by us (B(x) = x sin(x)) and we added it to the library. I will add more information about it or remove it at all.

**Comment by Happypig375** [comment]
Maybe "every" should be "very"?

**Comment by WhiteBlackGoose** [comment]
Yes, it should be
