### ISSUE TITLE
Add a way to solve for all variables in an equation or an equation system

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#24]
Currently only solving for one variable is supported.

**Comment by WhiteBlackGoose** [comment]
What do you mean by that? You can solve equation systems like that

**Comment by Happypig375** [comment]
Was thinking of an equivalent of Simplify for EquationSystems so that
- x+2y=3
- x+y=2
can be simplified to
- x = 1
- y = 1

**Comment by WhiteBlackGoose** [comment]
Solve this equation for each variable
`
Entity expr = "x + y - z";
expr.Solve("x");
expr.Solve("y");
expr.Solve("z");
`

**Comment by Happypig375** [comment]
But this requires knowing the variables in advance. `GetUniqueVariables` does not help here because `Solve` requires a list of VariableEntities, which is incompatible with EntitySet. Moreover, even with the help of LINQ to convert the EntitySet to a list of VariableEntities, a MathSException is still thrown with message `Amount of equations must be equal to that of vars`.

**Comment by Happypig375** [comment]
And your solution does not work for an EquationSystem.

**Comment by WhiteBlackGoose** [comment]
I don't understand your problem at all.
```
Entity expr = "x + y - z";
foreach (var v in MathS.GetUniqueVariables(expr))
    Console.WriteLine(v.ToString() + " = " + expr.Solve(v as VariableEntity));
```

**Comment by Happypig375** [comment]
>And your solution does not work for an EquationSystem.

**Comment by WhiteBlackGoose** [comment]
What do you want from equation systems? Are you sure what you are looking for is necessary and at the same time cannot be achived by the user through a couple of lines of code?

**Comment by Happypig375** [comment]
Superseded by #43
