### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#42]
**Describe the bug**
```cs
AngouriMath.MathS.Equations("a+b-c", "3a+3b-2c", "3a+4b-4c").Solve("a", "b", "c").Latexise()
```
`\begin{pmatrix}NaN + NaNi & -NaN + NaNi & NaN + NaNi+-NaN + NaNi\end{pmatrix}`

**Comment by MomoDeve** [comment]
fixed in last master commit
