### ISSUE TITLE
Extend EquationSystem solving to eliminate the number of equations = number of variables limitation

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#43]
e.g. `AngouriMath.MathS.Equations("a+b-c", "a-b-c").Solve("a", "b", "c")`

**Comment by WhiteBlackGoose** [comment]
Still unclear what you want. What is a possible scenario using it and at the same time it is too hard for the user to solve it in a loop for all variables?

**Comment by MomoDeve** [comment]
What behavior do you expect? EquationSystem is used to solve a system of equations with finite number of solutions, which is not true in your case

**Comment by Happypig375** [comment]
The solution is finite: a=c, b=0, c=a

**Comment by WhiteBlackGoose** [comment]
We decided not to implement such functional as there is still no need to solve N-set of equation over K variables for K > N. If you want to solve N equations for K variables you will get C(N, K) * F solutions, where F - number of solutions for N variables and for N equations. There is no need at all, and if you need to solve an equation or system for one specific variable - solve for it. Even WA [works similarly](https://www.wolframalpha.com/input/?i=a%2Bb-c%2Bd+%3D+0%2C+a-b-c%2Bd+%3D+0) (you see, it took 2 variables from the system) to AM in this case

**Comment by Happypig375** [comment]
>solve an equation or system for one specific variable

Solving an equation system for one variable is forbidden here:
https://github.com/asc-community/MathS/blob/58364d4ba64b9820e727840f72a5fc556be4df4c/AngouriMath/Functions/Algebra/Solver/EquationSolver.cs#L65-L68
So I do not understand how this is currently possible.

**Comment by WhiteBlackGoose** [comment]
I meant you include your variable into the list of variables you are going to solve for. If you need to solve for b, you include b. You cannot solve for more variables than the number of equations and what you suggest is unnecessary and not desired

**Comment by Happypig375** [comment]
>I meant you include your variable into the list of variables you are going to solve for. If you need to solve for b, you include b. You cannot solve for more variables than the number of equations

These are two contradictory statements. I need to solve for a, b and c, but this is more then the number of equations.

**Comment by WhiteBlackGoose** [comment]
You don't need to solve for a, b, and c. Not a possible scenario.

**Comment by Happypig375** [comment]
On the other hand, only including `b` will still hit the exception.

**Comment by Happypig375** [comment]
>Even WA works similarly (you see, it took 2 variables from the system) to AM in this case

Not really. Try `a^2+b=c+d, a-c^2=b+2d`: three solutions appear.

**Comment by WhiteBlackGoose** [comment]
As for your system, not sure, but then it shows two solutions for two variables. I don't know what is meant by the first set of solution as it doesn't make any sense.

**Comment by Happypig375** [comment]
>As a user, you can just go over the system in a loop and work out x for each of them

Can't this be built-in?

**Comment by WhiteBlackGoose** [comment]
There are too many problems to do now instead of something that would be never used.

**Comment by Happypig375** [comment]
Fine
