### ISSUE TITLE
Either expose IsTensoric() or make CrossProduct and DotProduct accept Entities

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#44]
Currently there is no way to properly support the × symbol and the · symbol on arbitrary entities.

**Comment by WhiteBlackGoose** [comment]
Thank you, it's been exposed. Now it's possible to write
```
Entity a = MathS.Vector(2, 3, 4);
Entity b = MathS.Vector(5, 6, 7);
if (a.IsTensoric() && b.IsTensoric())
    Console.WriteLine(MathS.ScalarProduct(a as Tensor, b as Tensor));
```
If you want, we may consider you as a long-term contributor. If interested, contact me by e-mail
