### ISSUE TITLE
Implement solving for log(2, x)=6

### ISSUE THREAD

**Issue by Happypig375** [asc-community/MathS#46]

**Comment by WhiteBlackGoose** [comment]
Will solve it in a little time, thank you. Have you consider our proposal of long-term contributing?

**Comment by Happypig375** [comment]
>Have you consider our proposal of long-term contributing?

Where?

**Comment by WhiteBlackGoose** [comment]
> If you want, we may consider you as a long-term contributor. If interested, contact me by e-mail

**Comment by Happypig375** [comment]
Sent an email, but seems you didn't receive it. What defines a "long term contributor"? I have my own library to maintain: https://github.com/verybadcat/CSharpMath
The reason I am here is that I am interested in implementing evaluation for the Editor component by calling into MathS. 
<table><td><img src="https://user-images.githubusercontent.com/19922066/80185029-3e53e000-863e-11ea-8bea-8b7f96ab2837.jpeg"/></td><td>
<img src="https://user-images.githubusercontent.com/19922066/80185543-15801a80-863f-11ea-9514-a59072c180b4.jpeg"/></td></table>
I can't dedicate all my time here, but I can report bugs, suggest enhancements and submit pull requests from time to time for sure.

**Comment by Happypig375** [comment]
@WhiteBlackGoose?

**Comment by WhiteBlackGoose** [comment]
What? The bug was fixed. As of the message, I sent you an e-mail

**Comment by Happypig375** [comment]
Hmm. Didn't receive.

**Comment by WhiteBlackGoose** [comment]
It couldn't manage to deliver the mail to [yourname]@outlook.com. Anyway, nothing special in the mail. I was just saying that "no problem" and thank you for your contributions.

**Comment by Happypig375** [comment]
Oh. My email address is not what you are describing. I sent an email titled "Hi -Happypig375" to your email posted on your profile to signify my email.
